version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: treasuremeasure/kittygram_backend  #зарегаться в dockerhub
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    image: treasuremeasure/kittygram_frontend  #зарегаться в dockerhub
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: treasuremeasure/kittygram_gateway #зарегаться в dockerhub
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
