version: '3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - "kittygram_network"
  backend:
    image: treasuremeasure/kittygram_backend  
    env_file: .env
    volumes:
      - media:/app/media
      - static:/app/collected_static
    networks:
      - "kittygram_network"
    depends_on:
      - db
    restart: always
  frontend:
    env_file: .env
    image: treasuremeasure/kittygram_frontend  
    networks:
      - "kittygram_network"
    depends_on:
      - backend
    volumes:
      - static_frontend:/app/build
  gateway:
    image: treasuremeasure/kittygram_gateway 
    env_file: .env
    ports:
      - 80:80
    networks:
      - "kittygram_network"
    volumes:
      - media:/var/www/media
      - static:/usr/share/nginx/html/backend
      - static_frontend:/usr/share/nginx/html/frontend
    depends_on:
      - backend
    restart: always

networks:
  kittygram_network:
    driver: "bridge"